<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="coverlet.msbuild" Version="10.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\NhatVuong.Application.csproj" />
    <ProjectReference Include="..\..\src\Domain\NhatVuong.Domain.csproj" />
    <ProjectReference Include="..\..\src\Adapters\Persistence\NhatVuong.Adapters.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Adapters\Scheduler\NhatVuong.Adapters.Scheduler.csproj" />
    <ProjectReference Include="..\..\src\Adapters\Rest\NhatVuong.Adapters.Rest.csproj" />
    <ProjectReference Include="..\..\src\Adapters\Mqtt\NhatVuong.Adapters.Mqtt.csproj" />
    <ProjectReference Include="..\..\src\Contracts\NhatVuong.Contracts.csproj" />
  </ItemGroup>

</Project>